### ISSUE TITLE
mac 使用问题

### ISSUE THREAD

**Issue by N3verL4nd** [ClassViewer/ClassViewer#15]
### 程序版本

3.2

### 运行环境
java version "1.8.0_171"

* 操作系统：
* JRE 版本：
java version "1.8.0_171"

### 详细描述

sudo java -jar ClassViewer-3.2.jar
Password:
[INFO] Not found Properties file
[Setting] viewer.debug=false
[Setting] viewer.color=true
[Setting] viewer.fonts.ui=Font[name=PingFang HK Regular, family=PingFang HK, style=Regular, size=14.0]
[Setting] viewer.fonts.text=null
[Setting] viewer.locale=zh_CN_#Hans
[Setting] viewer.disableSystemTitleBar=false
[Setting] viewer.skin=MODENA
[WARNING] Recent files not exists
objc[14525]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff95870c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1434c1cd8). One of the two will be used. Which one is undefined.

**Comment by Bertkiing** [comment]
Me, too.
<img width="750" alt="view" src="https://user-images.githubusercontent.com/19733128/89379477-716f3a80-d728-11ea-8a82-ed52e9c274eb.png">

**Comment by Glavo** [comment]
缺少 JavaFX 导致。v4 中实现了自动下载 JavaFX，请等待发布。
