### ISSUE TITLE
运行时菜单栏和工具栏缺失

### ISSUE THREAD

**Issue by Linuxea** [ClassViewer/ClassViewer#6]
只有一个空白的框框

效果图： http://ac913690.wiz03.com/share/s/2IAjqg1UbQ5m2Wf6he0PmGsV0lri7X2QBQlP2d4pIK3SBHnJ

**Comment by Linuxea** [comment]
在 idea 里面运行也是没有选项

**Comment by Glavo** [comment]
![image](https://user-images.githubusercontent.com/20694662/35684857-1d1dfdec-07a3-11e8-849d-b0e2c1a47520.png)
![image](https://user-images.githubusercontent.com/20694662/35684872-255d9fe4-07a3-11e8-8c79-e718963e153c.png)
我这边没有复现成功

**Comment by Glavo** [comment]
直接下载运行[ClassViewer-3.0-beta2](https://github.com/Glavo/ClassViewer/releases/download/v3.0-beta2/ClassViewer-3.0-beta2.jar)也会出现这个问题吗？

**Comment by Linuxea** [comment]
这个可以。我现在win7的电脑。明天回公司用小米笔记本试一下。

**Comment by Linuxea** [comment]
在小米上测试也可以了。就用这个吧。
